version: '3.8'
services:
  playwright-automated-tests:
    image: playwright-automated-tests
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run test
    volumes:
      - ./playwright-report/:/app/playwright-report


